from pip_audit_extra.requirement import clean_requirements

import pytest


@pytest.mark.parametrize(
	"src, expected_result",
	[
		("", ""),
		(
			"boolean.py==4.0\nCacheControl==0.14.1\ncertifi==2024.8.30\n",
			"boolean.py==4.0\nCacheControl==0.14.1\ncertifi==2024.8.30\n",
		),
		(
			# poetry
			"""\
boolean-py==4.0 ; python_full_version >= "3.8.1" and python_version < "4.0" \\
	--hash=sha256:17b9a181630e43dde1851d42bef546d616d5d9b4480357514597e78b203d06e4 \\
	--hash=sha256:2876f2051d7d6394a531d82dc6eb407faa0b01a0a0b3083817ccd7323b8d96bd
cachecontrol[filecache]==0.14.1 ; python_full_version >= "3.8.1" and python_full_version < "4.0.0" \\
	--hash=sha256:06ef916a1e4eb7dba9948cdfc9c76e749db2e02104a9a1277e8b642591a0f717 \\
	--hash=sha256:65e3abd62b06382ce3894df60dde9e0deb92aeb734724f68fa4f3b91e97206b9
certifi==2024.8.30 ; python_full_version >= "3.8.1" and python_full_version < "4.0.0" \\
	--hash=sha256:922820b53db7a7257ffbda3f597266d435245903d80737e34f8a45ff3e3230d8 \\
	--hash=sha256:bec941d2aa8195e248a60b31ff9f0558284cf01a52591ceda73ea9afffd69fd9
""",
			"boolean-py==4.0\ncachecontrol[filecache]==0.14.1\ncertifi==2024.8.30\n",
		),
		(
			# uv
			"""\
# This file was autogenerated by uv via the following command:
#    uv export
aniso8601==9.0.1 \\
	--hash=sha256:72e3117667eedf66951bb2d93f4296a56b94b078a8a95905a052611fb3f1b973 \\
	--hash=sha256:1d2b7ef82963909e93c4f24ce48d4de9e66009a21bf1c1e1c85bdd0812fe412f
arrow==1.3.0 \\
	--hash=sha256:d4540617648cb5f895730f1ad8c82a65f2dad0166f57b75f3ca54759c4d67a85 \\
	--hash=sha256:c728b120ebc00eb84e01882a6f5e7927a53960aa990ce7dd2b10f39005a67f80
asgiref==3.8.1 \\
	--hash=sha256:c343bd80a0bec947a9860adb4c432ffa7db769836c64238fc34bdc3fec84d590 \\
	--hash=sha256:3e1e3ecc849832fe52ccf2cb6686b7a55f82bb1d6aee72a58826471390335e47
""",
			"aniso8601==9.0.1\narrow==1.3.0\nasgiref==3.8.1\n",
		),
	],
)
def test_clean_requirements(src: str, expected_result: str):
	assert clean_requirements(src) == expected_result
